#!/usr/bin/env python3
"""
Autonomous CVE Remediation Script
Parses Trivy JSON output, identifies fixable vulnerabilities,
generates a patched Dockerfile, and opens a GitHub PR automatically.
"""

import json
import sys
import os
import subprocess
from datetime import datetime


def load_trivy_report(report_path):
    """Load and parse the Trivy JSON report."""
    with open(report_path, 'r') as f:
        return json.load(f)


def extract_fixable_vulns(report):
    """Extract vulnerabilities that have a fix available."""
    fixable = []

    for result in report.get('Results', []):
        for vuln in result.get('Vulnerabilities', []):
            if (vuln.get('FixedVersion') and
                    vuln.get('Severity') in ['CRITICAL', 'HIGH']):
                fixable.append({
                    'package': vuln.get('PkgName'),
                    'installed': vuln.get('InstalledVersion'),
                    'fixed': vuln.get('FixedVersion'),
                    'severity': vuln.get('Severity'),
                    'cve': vuln.get('VulnerabilityID'),
                    'title': vuln.get('Title', 'No title available'),
                    'target': result.get('Target')
                })

    return fixable


def generate_patched_dockerfile(original_path, fixable_vulns):
    """Generate a patched Dockerfile with security fixes applied."""
    with open(original_path, 'r') as f:
        content = f.read()

    # Add security update commands after the FROM line
    lines = content.split('\n')
    patched_lines = []
    inserted = False

    for line in lines:
        patched_lines.append(line)
        if line.startswith('FROM') and not inserted:
            # Add package update layer
            patched_lines.append('')
            patched_lines.append('# AUTO-REMEDIATION: Security patches applied by pipeline')
            patched_lines.append('# Generated: ' + datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC'))
            patched_lines.append('RUN apk update && apk upgrade --no-cache && rm -rf /var/cache/apk/*')
            inserted = True

    return '\n'.join(patched_lines)


def create_remediation_report(fixable_vulns, commit_sha, image_name):
    """Create a detailed remediation report for the PR."""
    report = f"""## 🔒 Automated Security Remediation Report

**Pipeline:** DevSecOps Autonomous Remediation
**Commit:** `{commit_sha}`
**Image:** `{image_name}`
**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
**Remediation Type:** Automated Dockerfile patch

---

## Vulnerabilities Detected & Remediated

| CVE | Package | Severity | Installed | Fixed |
|-----|---------|----------|-----------|-------|
"""
    for v in fixable_vulns:
        report += f"| {v['cve']} | {v['package']} | {v['severity']} | {v['installed']} | {v['fixed']} |\n"

    report += f"""
---

## Remediation Strategy

The pipeline detected **{len(fixable_vulns)} fixable vulnerabilities** and automatically applied the following remediation:

1. Added `apk update && apk upgrade --no-cache` to the Dockerfile
2. This forces Alpine to pull the latest patched versions of all system packages
3. A re-scan will be triggered on merge to validate the fix

## Next Steps

- [ ] Review this PR
- [ ] Merge to trigger re-scan
- [ ] Verify all CVEs are resolved in the follow-up scan
- [ ] Pipeline will auto-deploy if re-scan passes

---
*This PR was autonomously generated by the security pipeline. No human intervention was required for detection or remediation.*
"""
    return report


def open_github_pr(branch_name, report, commit_sha, vuln_count):
    """Create a GitHub PR using the GitHub CLI."""
    title = f"[AUTO-REMEDIATION] Fix {vuln_count} CRITICAL/HIGH CVEs detected in commit {commit_sha[:7]}"

    # Write report to temp file
    report_file = '/tmp/pr_body.md'
    with open(report_file, 'w') as f:
        f.write(report)

    # Create PR using gh CLI
    result = subprocess.run([
        'gh', 'pr', 'create',
        '--title', title,
        '--body-file', report_file,
        '--base', 'main',
        '--head', branch_name,
        '--label', 'security,automated-remediation'
    ], capture_output=True, text=True)

    if result.returncode == 0:
        print(f"✅ PR created successfully: {result.stdout.strip()}")
        return result.stdout.strip()
    else:
        print(f"❌ PR creation failed: {result.stderr}")
        return None


def main():
    report_path = os.environ.get('TRIVY_REPORT_PATH', 'trivy-report.json')
    commit_sha = os.environ.get('GITHUB_SHA', 'unknown')
    image_name = os.environ.get('IMAGE_NAME', 'devsecops-demo')
    dockerfile_path = os.environ.get('DOCKERFILE_PATH', 'app/Dockerfile')

    print(f"🔍 Loading Trivy report from: {report_path}")

    try:
        report = load_trivy_report(report_path)
    except FileNotFoundError:
        print(f"❌ Trivy report not found at {report_path}")
        sys.exit(1)

    fixable_vulns = extract_fixable_vulns(report)

    if not fixable_vulns:
        print("✅ No fixable CRITICAL/HIGH vulnerabilities found.")
        sys.exit(0)

    print(f"⚠️  Found {len(fixable_vulns)} fixable vulnerabilities:")
    for v in fixable_vulns:
        print(f"   - {v['cve']} ({v['severity']}): {v['package']} {v['installed']} → {v['fixed']}")

    # Generate patched Dockerfile
    print("\n🔧 Generating patched Dockerfile...")
    patched_content = generate_patched_dockerfile(dockerfile_path, fixable_vulns)

    patched_path = 'app/Dockerfile.patched'
    with open(patched_path, 'w') as f:
        f.write(patched_content)
    print(f"✅ Patched Dockerfile written to: {patched_path}")

    # Generate remediation report
    report_md = create_remediation_report(fixable_vulns, commit_sha, image_name)

    # Create remediation branch and PR
    branch_name = f"auto-remediation/{commit_sha[:7]}-fix-cves"
    print(f"\n📝 Creating remediation branch: {branch_name}")

    subprocess.run(['git', 'config', 'user.email', 'pipeline@devsecops-demo.com'])
    subprocess.run(['git', 'config', 'user.name', 'DevSecOps Pipeline'])
    subprocess.run(['git', 'checkout', '-b', branch_name])
    subprocess.run(['git', 'add', patched_path])
    subprocess.run(['git', 'commit', '-m',
                   f'fix(security): auto-remediate {len(fixable_vulns)} CVEs from commit {commit_sha[:7]}'])
    subprocess.run(['git', 'push', 'origin', branch_name])

    pr_url = open_github_pr(branch_name, report_md, commit_sha, len(fixable_vulns))

    if pr_url:
        print(f"\n🎉 Remediation complete!")
        print(f"   PR URL: {pr_url}")
        print(f"   Vulnerabilities addressed: {len(fixable_vulns)}")

        # Output for Splunk
        splunk_event = {
            "event_type": "auto_remediation",
            "commit": commit_sha,
            "vulns_found": len(fixable_vulns),
            "pr_url": pr_url,
            "status": "remediation_pr_opened"
        }
        print(f"\n📊 SPLUNK_EVENT: {json.dumps(splunk_event)}")
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == '__main__':
    main()
